language: java

matrix:
  include:
    - os: linux
      jdk: oraclejdk8
    - os: linux
      jdk: oraclejdk7
    - os: linux
      jdk: openjdk7

script:
- mvn -f kafka-connector/pom.xml clean verify
- mvn -f jms-light/pom.xml clean verify
- mvn -f load-test-framework/pom.xml clean verify
- mvn -f client/pom.xml clean verify
