language: java
matrix:
  include:
    - os: linux
      jdk: oraclejdk8
    - os: linux
      jdk: oraclejdk7
    - os: linux
      jdk: openjdk7

install:

script:
- mvn -f kafka-connector/pom.xml clean package
- mvn -f jms-light/pom.xml clean package
- mvn -f load-test-framework/pom.xml clean package
- mvn -f client/pom.xml package

