language: java

matrix:
  include:
    - os: linux
      jdk: oraclejdk8
    - os: linux
      jdk: oraclejdk7
    - os: linux
      jdk: openjdk7

script:
  - mvn -q -B -f jms-light/pom.xml clean verify
  - mvn -q -B -f kafka-connector/pom.xml clean verify
  - mvn -q -B -f client/pom.xml clean verify -Dmaven.javadoc.skip=true -Dgpg.skip=true -Djava.util.logging.config.file=client/src/test/resources/logging.properties
  - jdk_switcher use oraclejdk8
  - mvn -q -B -f load-test-framework/pom.xml clean verify
