language: java

matrix:
  include:
    - os: linux
      jdk: oraclejdk8
    - os: linux
      jdk: oraclejdk7
    - os: linux
      jdk: openjdk7

script:
  - mvn -q -f kafka-connector/pom.xml clean verify
  - mvn -q -f jms-light/pom.xml clean verify
  - mvn -q -f load-test-framework/pom.xml clean verify
  - mvn -q -f client/pom.xml clean verify
        -Dmaven.javadoc.skip=true
        -Dgpg.skip=true
        -Djava.util.logging.config.file=client/src/test/resources/logging.properties
